# project: EduManager 2026
# created: 2026-05-23 (Data)
# changed: 2026-05-23 (Data)

direction: right

alex: Alex / Teacher {
  shape: person
}

edumanager: EduManager 2026 {
  app: Application
  data: Local project data {
    shape: cylinder
  }

  app -> data: reads/writes
}

school: School context {
  students: Students
  rooms: Rooms
  timetable: Timetable
  seating: Seating arrangements
  roomsituation: konkrete raumsituation

  timetable -> rooms: uses
  seating -> students: places
  seating -> roomsituation: uses
  roomsituation -> rooms: depends on

}

alex -> edumanager.app: uses
edumanager.app -> school: supports work with
